name: generate github-contribution-grid-snake.svg
uses: Platane/snk/svg-only@v2
with:
  github_user_name: SaadARazzaq
  outputs: |
    dist/github-contribution-grid-snake.svg
    dist/github-contribution-grid-snake-dark.svg?palette=github-dark
