name: Generate Snake Eating Contribution Graph

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Generate Snake Animation
        run: npx snk generate

      - name: Commit and Push Changes
        run: |
          git config --global user.name SaadARazzaq
          git config --global user.email sabdurrazzaq124@gmail.com
          git add .
          git commit -m "Generate snake eating contribution graph"
          git push
